--- Makefile
+++ Makefile
@@ -98,7 +98,6 @@
 # Make.mach.<machine-name> defines all machine-dependent settings.
 #-----------------------------------------------------------------------
 
-#-include $(ENZO_DIR)/Make.mach.$(CONFIG_MACHINE)
 -include $(ENZO_DIR)/Make.mach.$(CONFIG_MACHINE)
 -include $(HOME)/.enzo/Make.mach.$(CONFIG_MACHINE)
 
@@ -112,25 +111,32 @@
 # MAKE ENZO BY DEFAULT
 #-----------------------------------------------------------------------
 
-all: $(EXE).exe
+all: MACHNOTES $(EXE).exe
 
 #-----------------------------------------------------------------------
 # MAKE AN EXECUTABLE
 #-----------------------------------------------------------------------
 
+MACHNOTES: 
+	@echo -e $(MACHINE_NOTES)
 
-%.exe: 	$(MODULES) autogen dep %.o $(OBJS_LIB)
-	@rm -f $@
+%.exe: 	$(MODULES) autogen dep %.o $(OBJS_LIB) MACHNOTES
+	@rm -f ${ENZO_DIR}/$@
 	@echo "Linking enzo executable. Type  cat $(OUTPUT)  in case it fails."
 	@(if [ $(VERBOSE) -eq 0 ]; then \
-		cd ../src/enzo; \
+		cd $(ENZO_DIR) ; \
 		$(LD) $(LDFLAGS) -o $*.exe $*.o $(OBJS_LIB) $(LIBS) >& $(OUTPUT) ; \
+		cd $(TOP_DIR)/$(PATCH) ; \
 	else \
-		$(LD) $(LDFLAGS) -o $(ENZO_DIR)/$*.exe $(ENZO_DIR)/$*.o $(ENZO_DIR)/$(OBJS_LIB) $(LIBS) >> $(OUTPUT) \
+		cd $(ENZO_DIR) \
+		$(LD) $(LDFLAGS) -o $*.exe $*.o $(OBJS_LIB) $(LIBS) >> $(OUTPUT) \
 		2>&1 ; \
+		cd $(TOP_DIR)/$(PATCH) ; \
 	fi)  
 	@(if [ -e $(ENZO_DIR)/$@ ] ; then  \
 		echo "Success!" ; \
+		if [ ! -e $(TOP_DIR)/bin ]; then mkdir $(TOP_DIR)/bin; fi; \
+                cp $(ENZO_DIR)/$(EXE).exe $(TOP_DIR)/bin/$(EXE); \
 	else \
 		echo "$(LD) $(LDFLAGS) -o $< $*.o $(OBJS_LIB) $(LIBS)" > temp1; \
 		cat temp1 $(OUTPUT) > temp2 ;\
@@ -154,67 +160,58 @@
 # Implicit rules
 #-----------------------------------------------------------------------
 
-.SUFFIXES: .c .C .src .src90 .f .f90 .o .cu
+.SUFFIXES: .c .C .F .F90 .o .cu
 
 # Inhibit removing any *.o files after compiling
 
-.PRECIOUS: %.o %.f %.f90
+.PRECIOUS: %.o 
 
-.src.f:
-	@$(CPP) $(DEFINES) $(CPPFLAGS) $< > $(ENZO_DIR)/$*.f
-.f.o:
+#.src.f:
+#	@$(CPP) $(DEFINES) $(CPPFLAGS) $< > $(ENZO_DIR)/$*.f
+.F.o:
 	@echo "Compiling $<"
 	@rm -f $(ENZO_DIR)/$@
 	@(if [ $(VERBOSE) -eq 0 ]; then \
-	  $(FC) -c -o $(ENZO_DIR)/$@ $(FFLAGS) $(ENZO_DIR)/$*.f >& $(OUTPUT) ; \
+		$(FC) -c -o $(ENZO_DIR)/$@ $(FFLAGS) $(DEFINES) $(ENZO_DIR)/$*.F >& $(OUTPUT) ; \
+		if [ ! -e $(ENZO_DIR)/$@ ]; then \
+		echo; \
+		echo "$(FC) -c -o $(ENZO_DIR)/$@ $(FFLAGS) $(DEFINES) $(ENZO_DIR)/$*.F"; \
+		echo; \
+	     	$(FC) -c -o $(ENZO_DIR)/$@ $(FFLAGS) $(DEFINES) $(ENZO_DIR)/$*.F; \
+		echo; \
+		exit 1; \
+	fi ; \
+	else \
+		$(FC) -c -o $(ENZO_DIR)/$@ $(FFLAGS) $(DEFINES) $(ENZO_DIR)/$*.f >> $(OUTPUT) 2>&1 ; \
+		if [ ! -e $(ENZO_DIR)/$@ ]; then \
+	     	echo "See $(OUTPUT) for error messages"; \
+	     	exit 1; \
+	fi ; \
+	fi)
+
+#.src90.f90:#
+#	@echo "Compiling $<"
+#	@$(CPP) $(DEFINES) $(CPPFLAGS) $< > $(ENZO_DIR)/$*.f90
+
+.F90.o:
+	@rm -f $(ENZO_DIR)/$@
+	@(if [ $(VERBOSE) -eq 0 ]; then \
+	  $(F90) -c -o $(ENZO_DIR)/$@ $(F90FLAGS) $(DEFINES) $(ENZO_DIR)/$*.F90 >& $(OUTPUT) ; \
 	  if [ ! -e $(ENZO_DIR)/$@ ]; then \
              echo; \
-             echo "$(CPP) $(DEFINES) $(CPPFLAGS) $*.src > $*.f"; \
-             echo "$(FC) -c -o $(ENZO_DIR)/$@ $(FFLAGS) $*.f"; \
+             echo "$(F90) -c -o $(ENZO_DIR)/$@ $(DEFINES) $(F90FLAGS) $(ENZO_DIR)/$*.F90"; \
              echo; \
-             $(CPP) $(DEFINES) $(CPPFLAGS) $(ENZO_DIR)/$*.src > $*.f; \
-             $(FC) -c -o $(ENZO_DIR)/$@ $(FFLAGS) $(ENZO_DIR)/$*.f; \
+             $(F90) -c -o $(ENZO_DIR)/$@ $(F90FLAGS) $(ENZO_DIR)/$*.F90; \
              echo; \
              exit 1; \
-          fi ; \
+	  fi ; \
 	else \
-	  $(FC) -c -o $(ENZO_DIR)/$@ $(FFLAGS) $(ENZO_DIR)/$*.f >> $(OUTPUT) 2>&1 ; \
+	  $(F90) -c -o $(ENZO_DIR)/$@ $(F90FLAGS) $(DEFINES) $(ENZO_DIR)/$*.F90 >> $(OUTPUT) 2>&1 ; \
 	  if [ ! -e $(ENZO_DIR)/$@ ]; then \
 	     echo "See $(OUTPUT) for error messages"; \
 	     exit 1; \
 	  fi ; \
 	fi)
-	@(if [ -e $(ENZO_DIR)/$@ ]; then \
-             touch -f $(ENZO_DIR)/$*.f; \
-          fi)
-
-.src90.f90:
-	@echo "Compiling $<"
-	@$(CPP) $(DEFINES) $(CPPFLAGS) $< > $(ENZO_DIR)/$*.f90
-.f90.o:
-	@rm -f $(ENZO_DIR)/$@
-	@(if [ $(VERBOSE) -eq 0 ]; then \
-	  $(F90) -c -o $(ENZO_DIR)/$@ $(F90FLAGS) $(ENZO_DIR)/$*.f90 >& $(OUTPUT) ; \
-	  if [ ! -e $(ENZO_DIR)/$@ ]; then \
-             echo; \
-             echo "$(CPP) $(DEFINES) $(CPPFLAGS) $(ENZO_DIR)/$*.src90 > $(ENZO_DIR)/$*.f90"; \
-             echo "$(F90) -c -o $(ENZO_DIR)/$@ $(F90FLAGS) $(ENZO_DIR)/$*.f90"; \
-             echo; \
-             $(CPP) $(DEFINES) $(CPPFLAGS) $(ENZO_DIR)/$*.src90 > $(ENZO_DIR)/$*.f90; \
-             $(F90) -c -o $(ENZO_DIR)/$@ $(F90FLAGS) $(ENZO_DIR)/$*.f90; \
-             echo; \
-             exit 1; \
-	  fi ; \
-	else \
-	  $(F90) -c -o $(ENZO_DIR)/$@ $(F90FLAGS) $(ENZO_DIR)/$*.f90 >> $(OUTPUT) 2>&1 ; \
-	  if [ ! -e $(ENZO_DIR)/$@ ]; then \
-	     echo "See $(OUTPUT) for error messages"; \
-	     exit 1; \
-	  fi ; \
-	fi)
-	@(if [ -e $(ENZO_DIR)/$@ ]; then \
-             rm -f $(ENZO_DIR)/$*.f90; \
-          fi)
 
 .c.o:
 	@rm -f $(ENZO_DIR)/$@
@@ -328,13 +325,6 @@
 	printf "#define ENZO_SVN_BRANCH \"\"\n" >> svn_version.def; \
 	fi
 
-# Determine Enzo version
-
-.PHONY: get-version
-get-version:
-	@$(SVN) info $(TOP_DIR) | awk '/URL/{print $$2}'      > $(TOP_DIR)/BRANCH
-	@$(SVN) info $(TOP_DIR) | awk '/Revision/{print $$2}' > $(TOP_DIR)/REVISION
-
 #-----------------------------------------------------------------------
 # Generate dependency file
 #-----------------------------------------------------------------------
@@ -359,26 +349,6 @@
 #	+(cd photons/ ; make photon)
 
 #-----------------------------------------------------------------------
-# INSTALL TARGET
-#-----------------------------------------------------------------------
-
-install: $(TOP_DIR)/bin
-	if [ ! -e $(TOP_DIR)/bin ]; then mkdir $(TOP_DIR)/bin; fi
-	-@cp $(EXE).exe $(TOP_DIR)/bin/$(EXE)
-	-@cp gridtests.exe $(TOP_DIR)/bin/gridtests
-	-@cp ealfloattests.exe $(TOP_DIR)/bin/ealfloattests
-	-@cp ealinttests.exe $(TOP_DIR)/bin/ealinttests
-	-@cp readgridtests.exe $(TOP_DIR)/bin/readgridtests
-	-@cp analysisbaseclasstests.exe $(TOP_DIR)/bin/analysisbaseclasstests
-	-$(MAKE) -s show-flags   >& $(TOP_DIR)/bin/$(EXE).show-flags
-	-$(MAKE) -s show-config  >& $(TOP_DIR)/bin/$(EXE).show-config
-	-$(MAKE) -s show-version >& $(TOP_DIR)/bin/$(EXE).show-version
-	-$(MAKE) -s show-diff    >& $(TOP_DIR)/bin/$(EXE).show-diff
-
-$(TOP_DIR)/bin:
-	mkdir $(TOP_DIR)/bin
-
-#-----------------------------------------------------------------------
 # HELP TARGET
 #-----------------------------------------------------------------------
 
@@ -407,10 +377,12 @@
 
 clean:
 	-@rm -f $(ENZO_DIR)/*.o $(ENZO_DIR)/uuid/*.o *.mod $(ENZO_DIR)/*.f $(ENZO_DIR)/*.f90 $(ENZO_DIR)/DEPEND.bak $(ENZO_DIR)/*~ $(OUTPUT) $(ENZO_DIR)/*.exe \
-          auto_show*.C svn_version.def $(ENZO_DIR)/hydro_rk/*.o temp.show*
+          auto_show*.C svn_version.def $(ENZO_DIR)/hydro_rk/*.o $(ENZO_DIR)/*.oo $(ENZO_DIR)/hydro_rk/*.oo temp.show* $(ENZO_DIR)/uuid/*.oo DEPEND
+	-@touch DEPEND
 
 #-----------------------------------------------------------------------
 # Include configuration targets
 #-----------------------------------------------------------------------
 
 include $(ENZO_DIR)/Make.config.targets
+# DO NOT DELETE
