#!/bin/csh

#  This file contains all of the executable information about enzo (restart
#  information, etc.  It assumes that all of the files required for the 
#  simulation (ring, enzo, the initial conditions and parameter files, and
#  any files needed for cooling curves, etc.) are in the same directory as
#  this script.
#

#  Assuming this simulation is very large, this line runs ring, which cuts
#  up the particle position and velocity files into N files, where N is the
#  total number of processors used in the simulation.  poe (mpi scheduler
#  for blue horizon) does not need to be told the number of cpus).
poe ring ParticlePositions ParticleVelocities

#  This line runs enzo, with the debug option on ( -d option), and
#  dumps all of the data that appears in stdout into a file called
#  LogFile

poe enzo -d ParameterFile > LogFile

