#!/bin/tcsh

set Old = $1
set New = $2
set OK = $3
if( $OK == "" ) then
 set list = `grep -l $Old $a`
else
 set list = `grep -l $Old $a |egrep -v $OK`
endif

foreach i ($list)
echo =================== $i ================
sed -n "s,$Old,$New,p" $i
end

if( $#list > 0 ) then
sed -i "s,$Old,$New,g" $list
endif
#end
