#!/bin/tcsh

set OKfiles = "SetDefaultGlobalValues.C|global_data.h|ReadParameterFile.C|MHDCT_ParameterJuggle.C"

NameChangeTool MHD_Used useMHDCT $OKfiles

NameChangeTool pout.h DaveTools.h

NameChangeTool WriteInThisA SingleGridDumpList

NameChangeTool WriteInThisF CheckForSingleGridDump
#end
