build:
	$(MAKE) -C enzohop
	$(MAKE) -C inits
	$(MAKE) -C ring
	$(MAKE) -C enzo
	$(MAKE) -C anyl
clean:
	$(MAKE) -C enzohop clean
	$(MAKE) -C inits clean
	$(MAKE) -C ring  clean
	$(MAKE) -C enzo  clean
	$(MAKE) -C anyl  clean
